### ISSUE TITLE
关于您博客文章的一点小问题

### ISSUE THREAD

**Issue by Evyde** [kaoet/kaoet.github.io#1]
@kaoet 您好，首先很抱歉在Github Issues打扰您。由于我没有找到合适的可以联系到您的方式，所以才在这里提出问题，如果打扰到您，还请海涵。
您博客目前有一篇文章：[《高可用性翻墙路由：2. VPN 的搭建》](https://www.kaoet.me/2021/08/14/ha-gfw-router-vpn)，其中提到了使用IPSec/WireGuard组建VPN。但据说这两种方案已经可以被GFW精准识别，请问

1. 您在使用过程中，通过这两种方案部属的服务器有没有出现被墙的问题？
2. 如果容易被墙，那么有无其它办法可以将各服务器进行组网（例如使用混淆较好的其它软件作为前置代理/采用带有第三方中转服务器的组网软件）？

希望您不吝赐教。

另外，希望您可以给博客添加留言功能，据我所知，类似“多说”这样的第三方留言板适用于静态博客。

**Comment by kaoet** [comment]
关于识别问题，无可奉告。
关于留言问题，目前暂时没有功夫做留言的管理，暂不考虑。

**Comment by Evyde** [comment]
> 关于识别问题，无可奉告。
> 关于留言问题，目前暂时没有功夫做留言的管理，暂不考虑。

感谢您的回复。
关于识别问题，我搜索到WireGuard确实[可以被精准识别](https://lists.zx2c4.com/pipermail/wireguard/2018-September/003289.html)，但目前据反应仅仅是QoS，也并非完全不可使用。另外，我也发现可以采用WireGuard over Vless的方法来进行混淆，暂时应该不是问题了。
再次感谢您的耐心回复，美好的祝福送给您。
